name: Verify gschema
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  check_gschema:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Run compile_gschema.sh
      run: ./scripts/compile_gschema.sh

    - name: Check for changes in schemas
      run: |
        if ! git diff --exit-code -- o-ring@christgr1.github.io/schemas/gschemas.compile; then
          echo "Error: Compiled schemas are not up to date. Please run 'scripts/compile_gschema.sh' and commit the changes."
          git status
          exit 1
        else
          echo "Compiled schemas are up to date."
        fi
